-- ========================================
-- 100レシピの追加投入（主菜50、副菜30、汁物20）
-- 現在のスキーマに合わせて簡素化版
-- ========================================

-- ========================================
-- 主菜 50品
-- ========================================
INSERT INTO recipes (recipe_id, title, role, description, cuisine, difficulty, time_min, primary_protein, cost_tier, steps_json, substitutes_json, tags_json, season_json) VALUES
('main_011', '鶏の唐揚げ', 'main', '定番の唐揚げ', 'japanese', 'normal', 35, 'chicken', 500, '["鶏肉に下味をつける", "片栗粉をまぶす", "170度で揚げる"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_012', '豚カツ', 'main', 'サクサクのとんかつ', 'japanese', 'normal', 30, 'pork', 800, '["豚肉を叩いて伸ばす", "パン粉をつける", "180度で揚げる"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_013', '鮭の塩焼き', 'main', 'シンプルな鮭の塩焼き', 'japanese', 'easy', 20, 'fish', 500, '["鮭に塩をふる", "グリルで焼く"]', '[]', '["grilled"]', '["spring","summer","autumn","winter"]'),
('main_014', 'サバの味噌煮', 'main', '味噌で煮込んだサバ', 'japanese', 'normal', 30, 'fish', 500, '["サバを湯通しする", "味噌と調味料で煮込む"]', '[]', '["simmered"]', '["spring","summer","autumn","winter"]'),
('main_015', '牛丼', 'main', '甘辛い牛肉の丼', 'japanese', 'easy', 25, 'beef', 800, '["牛肉と玉ねぎを炒める", "醤油とみりんで味付け", "ご飯にかける"]', '[]', '["rice_bowl"]', '["spring","summer","autumn","winter"]'),
('main_016', '親子丼', 'main', '鶏肉と卵の丼', 'japanese', 'easy', 25, 'chicken', 500, '["鶏肉と玉ねぎを煮る", "溶き卵を加える", "ご飯にかける"]', '[]', '["rice_bowl"]', '["spring","summer","autumn","winter"]'),
('main_017', 'カツ丼', 'main', 'とんかつの卵とじ丼', 'japanese', 'normal', 20, 'pork', 800, '["とんかつを切る", "玉ねぎと煮る", "卵でとじる"]', '[]', '["rice_bowl"]', '["spring","summer","autumn","winter"]'),
('main_018', 'エビフライ', 'main', 'サクサクのエビフライ', 'japanese', 'normal', 30, 'other', 1000, '["エビの下処理", "パン粉をつける", "180度で揚げる"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_019', 'ハンバーグ', 'main', 'ジューシーなハンバーグ', 'western', 'normal', 40, 'beef', 500, '["挽肉と玉ねぎを混ぜる", "成形して焼く", "ソースをかける"]', '[]', '["meat"]', '["spring","summer","autumn","winter"]'),
('main_020', 'ミートボール', 'main', '甘酢あんのミートボール', 'western', 'normal', 35, 'beef', 500, '["挽肉を丸める", "揚げる", "甘酢あんを絡める"]', '[]', '["meat"]', '["spring","summer","autumn","winter"]'),
('main_021', '麻婆豆腐', 'main', 'ピリ辛の麻婆豆腐', 'chinese', 'normal', 25, 'soy', 500, '["挽肉を炒める", "豆腐を加える", "豆板醤で味付け"]', '[]', '["spicy"]', '["spring","summer","autumn","winter"]'),
('main_022', '回鍋肉', 'main', 'キャベツと豚肉の炒め物', 'chinese', 'normal', 25, 'pork', 500, '["豚肉を炒める", "キャベツを加える", "味噌で味付け"]', '[]', '["stir_fry"]', '["spring","summer","autumn","winter"]'),
('main_023', '青椒肉絲', 'main', 'ピーマンと豚肉の炒め物', 'chinese', 'normal', 25, 'pork', 500, '["豚肉を切る", "ピーマンと炒める", "オイスターソースで味付け"]', '[]', '["stir_fry"]', '["spring","summer","autumn","winter"]'),
('main_024', 'エビチリ', 'main', 'ピリ辛のエビチリ', 'chinese', 'normal', 30, 'other', 1000, '["エビの下処理", "チリソースで炒める"]', '[]', '["spicy"]', '["spring","summer","autumn","winter"]'),
('main_025', '酢豚', 'main', '甘酢あんの酢豚', 'chinese', 'hard', 40, 'pork', 800, '["豚肉を揚げる", "野菜を炒める", "甘酢あんを絡める"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_026', 'カレーライス', 'main', '定番のカレー', 'western', 'easy', 45, 'beef', 500, '["野菜と肉を炒める", "水を加えて煮込む", "カレールーを加える"]', '[]', '["curry"]', '["spring","summer","autumn","winter"]'),
('main_027', 'ハヤシライス', 'main', 'デミグラスソースのハヤシ', 'western', 'normal', 40, 'beef', 800, '["牛肉と玉ねぎを炒める", "デミグラスソースで煮込む"]', '[]', '["rice"]', '["spring","summer","autumn","winter"]'),
('main_028', 'オムライス', 'main', 'ふわとろオムライス', 'western', 'normal', 30, 'egg', 500, '["チキンライスを作る", "卵を焼く", "ライスにのせる"]', '[]', '["rice"]', '["spring","summer","autumn","winter"]'),
('main_029', 'グラタン', 'main', 'クリーミーなグラタン', 'western', 'hard', 45, 'chicken', 800, '["ホワイトソースを作る", "具材と混ぜる", "オーブンで焼く"]', '[]', '["baked"]', '["spring","autumn","winter"]'),
('main_030', 'シチュー', 'main', 'クリームシチュー', 'western', 'easy', 45, 'chicken', 800, '["野菜と肉を炒める", "牛乳を加える", "シチューの素で仕上げ"]', '[]', '["stew"]', '["spring","autumn","winter"]'),
('main_031', 'ロールキャベツ', 'main', 'コトコト煮込んだロールキャベツ', 'western', 'hard', 70, 'beef', 800, '["キャベツを茹でる", "肉だねを巻く", "トマトソースで煮込む"]', '[]', '["stew"]', '["spring","summer","autumn","winter"]'),
('main_032', 'ポークソテー', 'main', 'ジューシーなポークソテー', 'western', 'easy', 25, 'pork', 800, '["豚肉に塩コショウ", "フライパンで焼く", "ソースをかける"]', '[]', '["grilled"]', '["spring","summer","autumn","winter"]'),
('main_033', 'ステーキ', 'main', '牛肉のステーキ', 'western', 'normal', 20, 'beef', 1500, '["牛肉に塩コショウ", "強火で焼く", "休ませて切る"]', '[]', '["grilled"]', '["spring","summer","autumn","winter"]'),
('main_034', 'チキン南蛮', 'main', 'タルタルソースのチキン南蛮', 'japanese', 'normal', 40, 'chicken', 500, '["鶏肉を揚げる", "南蛮酢に漬ける", "タルタルソースをかける"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_035', '照り焼きチキン', 'main', '甘辛い照り焼き', 'japanese', 'easy', 25, 'chicken', 500, '["鶏肉を焼く", "照り焼きソースを絡める"]', '[]', '["grilled"]', '["spring","summer","autumn","winter"]'),
('main_036', '鶏の胸肉ソテー', 'main', 'ヘルシーな鶏胸肉', 'western', 'easy', 25, 'chicken', 500, '["鶏胸肉を叩く", "焼く", "レモンソースをかける"]', '[]', '["grilled"]', '["spring","summer","autumn","winter"]'),
('main_037', '豚の角煮', 'main', 'とろとろの角煮', 'japanese', 'hard', 110, 'pork', 800, '["豚肉を下茹で", "調味料で煮込む", "煮卵を添える"]', '[]', '["simmered"]', '["spring","autumn","winter"]'),
('main_038', 'ぶり大根', 'main', 'ぶりと大根の煮物', 'japanese', 'normal', 55, 'fish', 800, '["ぶりを湯通し", "大根と煮込む"]', '[]', '["simmered"]', '["autumn","winter"]'),
('main_039', 'ぶりの照り焼き', 'main', '照り焼きソースのぶり', 'japanese', 'easy', 25, 'fish', 800, '["ぶりを焼く", "照り焼きソースを絡める"]', '[]', '["grilled"]', '["autumn","winter"]'),
('main_040', '鯖の竜田揚げ', 'main', '下味をつけた鯖の揚げ物', 'japanese', 'normal', 30, 'fish', 500, '["鯖に下味", "片栗粉をまぶす", "揚げる"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_041', 'アジフライ', 'main', '定番のアジフライ', 'japanese', 'normal', 30, 'fish', 500, '["アジの下処理", "パン粉をつける", "揚げる"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_042', '焼き魚（サンマ）', 'main', '秋の味覚サンマ', 'japanese', 'easy', 20, 'fish', 500, '["サンマに塩", "グリルで焼く"]', '[]', '["grilled"]', '["autumn"]'),
('main_043', '鮭のムニエル', 'main', 'バター風味の鮭', 'western', 'easy', 25, 'fish', 800, '["鮭に小麦粉", "バターで焼く"]', '[]', '["grilled"]', '["spring","summer","autumn","winter"]'),
('main_044', '白身魚のフライ', 'main', 'サクサクの白身魚', 'western', 'normal', 25, 'fish', 800, '["白身魚にパン粉", "揚げる"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('main_045', '豚キムチ', 'main', 'ピリ辛豚キムチ', 'other', 'easy', 20, 'pork', 500, '["豚肉を炒める", "キムチを加える", "炒め合わせる"]', '[]', '["spicy"]', '["spring","summer","autumn","winter"]'),
('main_046', 'ビビンバ', 'main', '韓国の混ぜご飯', 'other', 'normal', 40, 'beef', 800, '["ナムルを作る", "肉を炒める", "ご飯にのせる"]', '[]', '["rice"]', '["spring","summer","autumn","winter"]'),
('main_047', 'プルコギ', 'main', '甘辛い韓国風焼肉', 'other', 'easy', 35, 'beef', 1000, '["牛肉を漬け込む", "野菜と炒める"]', '[]', '["stir_fry"]', '["spring","summer","autumn","winter"]'),
('main_048', 'チャプチェ', 'main', '春雨の炒め物', 'other', 'normal', 35, 'beef', 500, '["春雨を茹でる", "野菜と肉を炒める", "春雨と混ぜる"]', '[]', '["stir_fry"]', '["spring","summer","autumn","winter"]'),
('main_049', 'タコス', 'main', 'メキシコのタコス', 'other', 'normal', 35, 'beef', 800, '["挽肉を炒める", "トルティーヤで包む", "野菜をのせる"]', '[]', '["wrap"]', '["spring","summer","autumn","winter"]'),
('main_050', 'チキンカレー', 'main', 'スパイシーなチキンカレー', 'other', 'normal', 45, 'chicken', 500, '["鶏肉を炒める", "カレー粉で味付け", "煮込む"]', '[]', '["curry"]', '["spring","summer","autumn","winter"]'),
('main_051', 'ドライカレー', 'main', 'パラパラのドライカレー', 'other', 'easy', 25, 'beef', 500, '["挽肉を炒める", "カレー粉で炒める", "ご飯と混ぜる"]', '[]', '["curry"]', '["spring","summer","autumn","winter"]'),
('main_052', '鶏の水炊き', 'main', 'あっさり水炊き鍋', 'japanese', 'easy', 45, 'chicken', 500, '["鶏肉と野菜を煮る", "ポン酢で食べる"]', '[]', '["nabe"]', '["autumn","winter"]'),
('main_053', 'すき焼き', 'main', '甘辛いすき焼き', 'japanese', 'normal', 40, 'beef', 1500, '["牛肉と野菜を煮る", "溶き卵につけて食べる"]', '[]', '["nabe"]', '["autumn","winter"]'),
('main_054', 'しゃぶしゃぶ', 'main', 'さっぱりしゃぶしゃぶ', 'japanese', 'easy', 35, 'beef', 1200, '["昆布だしを沸かす", "肉と野菜をしゃぶしゃぶ", "ポン酢で食べる"]', '[]', '["nabe"]', '["autumn","winter"]'),
('main_055', 'キムチ鍋', 'main', 'ピリ辛キムチ鍋', 'other', 'easy', 40, 'pork', 500, '["キムチを炒める", "だしを加える", "肉と野菜を煮る"]', '[]', '["nabe"]', '["autumn","winter"]'),
('main_056', '餃子', 'main', 'パリパリの焼き餃子', 'chinese', 'hard', 45, 'pork', 500, '["餃子の具を作る", "皮で包む", "焼く"]', '[]', '["dumpling"]', '["spring","summer","autumn","winter"]'),
('main_057', 'チャーハン', 'main', 'パラパラチャーハン', 'chinese', 'easy', 20, 'egg', 500, '["ご飯と卵を炒める", "具材を加える", "調味料で味付け"]', '[]', '["rice"]', '["spring","summer","autumn","winter"]'),
('main_058', '天津飯', 'main', 'あんかけ卵の天津飯', 'chinese', 'easy', 25, 'egg', 500, '["卵を焼く", "あんを作る", "ご飯にのせる"]', '[]', '["rice"]', '["spring","summer","autumn","winter"]'),
('main_059', 'オムレツ', 'main', 'ふわふわオムレツ', 'western', 'normal', 20, 'egg', 300, '["卵を溶く", "具材を加える", "半熟に焼く"]', '[]', '["egg"]', '["spring","summer","autumn","winter"]'),
('main_060', '目玉焼き', 'main', 'シンプル目玉焼き', 'western', 'easy', 10, 'egg', 300, '["フライパンで焼く", "塩コショウ"]', '[]', '["egg"]', '["spring","summer","autumn","winter"]');

-- ========================================
-- 副菜 30品
-- ========================================
INSERT INTO recipes (recipe_id, title, role, description, cuisine, difficulty, time_min, primary_protein, cost_tier, steps_json, substitutes_json, tags_json, season_json) VALUES
('side_011', 'ポテトサラダ', 'side', 'クリーミーなポテトサラダ', 'western', 'easy', 35, 'other', 300, '["じゃがいもを茹でる", "つぶす", "マヨネーズで和える"]', '[]', '["salad"]', '["spring","summer","autumn","winter"]'),
('side_012', 'マカロニサラダ', 'side', 'マヨネーズのマカロニサラダ', 'western', 'easy', 25, 'other', 300, '["マカロニを茹でる", "野菜と混ぜる", "マヨネーズで和える"]', '[]', '["salad"]', '["spring","summer","autumn","winter"]'),
('side_013', 'コールスロー', 'side', 'さっぱりコールスロー', 'western', 'easy', 10, 'other', 300, '["キャベツを千切り", "ドレッシングで和える"]', '[]', '["salad"]', '["spring","summer","autumn","winter"]'),
('side_014', 'ひじきの煮物', 'side', '栄養満点ひじき', 'japanese', 'easy', 30, 'other', 300, '["ひじきを戻す", "油揚げと煮る"]', '[]', '["simmered"]', '["spring","summer","autumn","winter"]'),
('side_015', '切り干し大根', 'side', '甘辛い切り干し大根', 'japanese', 'easy', 35, 'other', 300, '["切り干し大根を戻す", "油揚げと煮る"]', '[]', '["simmered"]', '["spring","summer","autumn","winter"]'),
('side_016', 'かぼちゃの煮物', 'side', 'ホクホクかぼちゃ', 'japanese', 'easy', 30, 'other', 300, '["かぼちゃを切る", "だしで煮る"]', '[]', '["simmered"]', '["summer","autumn","winter"]'),
('side_017', '里芋の煮物', 'side', 'ねっとり里芋', 'japanese', 'normal', 40, 'other', 300, '["里芋の皮を剥く", "だしで煮る"]', '[]', '["simmered"]', '["autumn","winter"]'),
('side_018', '大学芋', 'side', '甘いカリカリ大学芋', 'japanese', 'normal', 30, 'other', 300, '["さつまいもを揚げる", "蜜を絡める", "ごまをふる"]', '[]', '["sweet"]', '["autumn","winter"]'),
('side_019', '筑前煮', 'side', '根菜たっぷりの煮物', 'japanese', 'normal', 50, 'chicken', 500, '["鶏肉と根菜を炒める", "だしで煮る"]', '[]', '["simmered"]', '["spring","autumn","winter"]'),
('side_020', 'きんぴらごぼう', 'side', 'ピリ辛きんぴら', 'japanese', 'easy', 20, 'other', 300, '["ごぼうと人参を切る", "炒める", "醤油で味付け"]', '[]', '["stir_fry"]', '["spring","summer","autumn","winter"]'),
('side_021', 'ほうれん草のおひたし', 'side', 'さっぱりおひたし', 'japanese', 'easy', 10, 'other', 300, '["ほうれん草を茹でる", "だしで味付け"]', '[]', '["boiled"]', '["spring","summer","autumn","winter"]'),
('side_022', '小松菜のおひたし', 'side', '栄養たっぷり小松菜', 'japanese', 'easy', 10, 'other', 300, '["小松菜を茹でる", "だしで味付け"]', '[]', '["boiled"]', '["spring","summer","autumn","winter"]'),
('side_023', 'ブロッコリーのサラダ', 'side', 'シャキシャキブロッコリー', 'western', 'easy', 15, 'other', 300, '["ブロッコリーを茹でる", "ドレッシングで和える"]', '[]', '["salad"]', '["spring","summer","autumn","winter"]'),
('side_024', 'トマトサラダ', 'side', 'さっぱりトマト', 'western', 'easy', 5, 'other', 300, '["トマトを切る", "オリーブオイルをかける"]', '[]', '["salad"]', '["spring","summer","autumn"]'),
('side_025', 'きゅうりの酢の物', 'side', 'さっぱり酢の物', 'japanese', 'easy', 10, 'other', 300, '["きゅうりを切る", "塩もみ", "酢で和える"]', '[]', '["vinegar"]', '["spring","summer","autumn","winter"]'),
('side_026', 'わかめの酢の物', 'side', 'さっぱりわかめ', 'japanese', 'easy', 10, 'other', 300, '["わかめを戻す", "きゅうりと混ぜる", "酢で和える"]', '[]', '["vinegar"]', '["spring","summer","autumn","winter"]'),
('side_027', '冷奴', 'side', 'さっぱり冷奴', 'japanese', 'easy', 5, 'soy', 300, '["豆腐を切る", "薬味をのせる"]', '[]', '["cold"]', '["spring","summer","autumn"]'),
('side_028', '揚げ出し豆腐', 'side', 'カリッと揚げ豆腐', 'japanese', 'normal', 25, 'soy', 300, '["豆腐に片栗粉", "揚げる", "だしをかける"]', '[]', '["fried"]', '["spring","summer","autumn","winter"]'),
('side_029', 'もやし炒め', 'side', 'シャキシャキもやし', 'chinese', 'easy', 10, 'other', 300, '["もやしを炒める", "塩コショウで味付け"]', '[]', '["stir_fry"]', '["spring","summer","autumn","winter"]'),
('side_030', 'ナムル', 'side', '韓国風ナムル', 'other', 'easy', 20, 'other', 300, '["野菜を茹でる", "ごま油で和える"]', '[]', '["salad"]', '["spring","summer","autumn","winter"]'),
('side_031', '枝豆', 'side', 'シンプル枝豆', 'japanese', 'easy', 15, 'soy', 300, '["枝豆を茹でる", "塩をふる"]', '[]', '["boiled"]', '["summer"]'),
('side_032', '卯の花', 'side', 'おからの煮物', 'japanese', 'easy', 25, 'soy', 300, '["おからと野菜を炒める", "だしで煮る"]', '[]', '["simmered"]', '["spring","summer","autumn","winter"]'),
('side_033', 'アスパラのベーコン巻き', 'side', '洋風副菜', 'western', 'easy', 20, 'other', 500, '["アスパラにベーコンを巻く", "焼く"]', '[]', '["grilled"]', '["spring","summer"]'),
('side_034', 'いんげんの胡麻和え', 'side', '胡麻の風味', 'japanese', 'easy', 15, 'other', 300, '["いんげんを茹でる", "胡麻で和える"]', '[]', '["boiled"]', '["spring","summer","autumn"]'),
('side_035', '白菜の浅漬け', 'side', 'さっぱり漬物', 'japanese', 'easy', 10, 'other', 300, '["白菜を切る", "塩で漬ける"]', '[]', '["pickled"]', '["autumn","winter"]'),
('side_036', '茄子の揚げ浸し', 'side', 'ジューシー茄子', 'japanese', 'normal', 25, 'other', 300, '["茄子を揚げる", "だしに浸す"]', '[]', '["fried"]', '["summer","autumn"]'),
('side_037', 'ピーマンの肉詰め', 'side', 'ジューシー肉詰め', 'western', 'normal', 30, 'beef', 500, '["ピーマンに肉を詰める", "焼く"]', '[]', '["grilled"]', '["spring","summer","autumn"]'),
('side_038', 'レンコンきんぴら', 'side', 'シャキシャキレンコン', 'japanese', 'easy', 20, 'other', 300, '["レンコンを切る", "炒める", "醤油で味付け"]', '[]', '["stir_fry"]', '["autumn","winter"]'),
('side_039', 'キャベツの千切り', 'side', 'シンプルキャベツ', 'japanese', 'easy', 5, 'other', 300, '["キャベツを千切り"]', '[]', '["raw"]', '["spring","summer","autumn","winter"]'),
('side_040', '温野菜', 'side', 'ヘルシー温野菜', 'western', 'easy', 25, 'other', 300, '["野菜を蒸す", "ドレッシングをかける"]', '[]', '["steamed"]', '["spring","summer","autumn","winter"]');

-- ========================================
-- 汁物 20品
-- ========================================
INSERT INTO recipes (recipe_id, title, role, description, cuisine, difficulty, time_min, primary_protein, cost_tier, steps_json, substitutes_json, tags_json, season_json) VALUES
('soup_011', '豚汁', 'soup', '具だくさんの豚汁', 'japanese', 'easy', 30, 'pork', 500, '["豚肉と根菜を煮る", "味噌で味付け"]', '[]', '["miso"]', '["spring","autumn","winter"]'),
('soup_012', 'けんちん汁', 'soup', '精進料理の汁', 'japanese', 'normal', 35, 'soy', 300, '["根菜を炒める", "だしで煮る", "醤油で味付け"]', '[]', '["clear"]', '["spring","autumn","winter"]'),
('soup_013', 'かき玉汁', 'soup', 'ふわふわ卵の汁', 'japanese', 'easy', 15, 'egg', 300, '["だしを沸かす", "溶き卵を流し入れる"]', '[]', '["clear"]', '["spring","summer","autumn","winter"]'),
('soup_014', '具だくさん味噌汁', 'soup', '野菜たっぷり味噌汁', 'japanese', 'easy', 25, 'soy', 300, '["野菜を煮る", "味噌で味付け"]', '[]', '["miso"]', '["spring","summer","autumn","winter"]'),
('soup_015', 'あさりの味噌汁', 'soup', '出汁の効いたあさり汁', 'japanese', 'normal', 25, 'other', 500, '["あさりの砂抜き", "煮る", "味噌で味付け"]', '[]', '["miso"]', '["spring","summer"]'),
('soup_016', 'しじみ汁', 'soup', '肝臓に優しいしじみ', 'japanese', 'easy', 20, 'other', 300, '["しじみを煮る", "味噌で味付け"]', '[]', '["miso"]', '["spring","summer","autumn","winter"]'),
('soup_017', '中華スープ', 'soup', 'さっぱり中華スープ', 'chinese', 'easy', 15, 'other', 300, '["鶏ガラスープを沸かす", "野菜を煮る", "塩で味付け"]', '[]', '["clear"]', '["spring","summer","autumn","winter"]'),
('soup_018', 'コーンスープ', 'soup', 'クリーミーなコーンスープ', 'western', 'easy', 20, 'other', 300, '["コーンを煮る", "牛乳を加える", "塩で味付け"]', '[]', '["creamy"]', '["spring","summer","autumn","winter"]'),
('soup_019', 'オニオンスープ', 'soup', '甘い玉ねぎのスープ', 'western', 'normal', 30, 'other', 300, '["玉ねぎを炒める", "コンソメで煮る"]', '[]', '["clear"]', '["spring","summer","autumn","winter"]'),
('soup_020', 'ミネストローネ', 'soup', 'イタリアの野菜スープ', 'other', 'normal', 45, 'other', 500, '["野菜を炒める", "トマト缶で煮る"]', '[]', '["tomato"]', '["spring","summer","autumn","winter"]'),
('soup_021', 'クラムチャウダー', 'soup', 'クリーミーなクラムチャウダー', 'western', 'normal', 40, 'other', 800, '["あさりを煮る", "野菜を加える", "牛乳でクリーミーに"]', '[]', '["creamy"]', '["spring","summer","autumn","winter"]'),
('soup_022', 'わかめスープ', 'soup', 'さっぱりわかめスープ', 'other', 'easy', 15, 'other', 300, '["わかめを戻す", "鶏ガラスープで煮る"]', '[]', '["clear"]', '["spring","summer","autumn","winter"]'),
('soup_023', 'ユッケジャンスープ', 'soup', 'ピリ辛韓国スープ', 'other', 'normal', 45, 'beef', 800, '["牛肉と野菜を煮る", "コチュジャンで味付け"]', '[]', '["spicy"]', '["spring","summer","autumn","winter"]'),
('soup_024', 'トムヤムクン', 'soup', 'タイのエビスープ', 'other', 'normal', 25, 'other', 800, '["エビと野菜を煮る", "トムヤムペーストで味付け"]', '[]', '["spicy"]', '["spring","summer","autumn","winter"]'),
('soup_025', 'ポトフ', 'soup', 'フランスの野菜煮込み', 'western', 'easy', 55, 'chicken', 500, '["野菜と肉を煮込む", "コンソメで味付け"]', '[]', '["stew"]', '["spring","autumn","winter"]'),
('soup_026', 'ガスパチョ', 'soup', '冷製トマトスープ', 'other', 'easy', 15, 'other', 300, '["野菜をミキサーにかける", "冷やす"]', '[]', '["cold"]', '["summer"]'),
('soup_027', 'ビシソワーズ', 'soup', '冷製じゃがいもスープ', 'western', 'normal', 45, 'other', 300, '["じゃがいもを煮る", "ミキサーにかける", "牛乳を加えて冷やす"]', '[]', '["cold"]', '["summer"]'),
('soup_028', '卵スープ', 'soup', 'シンプル卵スープ', 'chinese', 'easy', 15, 'egg', 300, '["鶏ガラスープを沸かす", "溶き卵を流し入れる"]', '[]', '["clear"]', '["spring","summer","autumn","winter"]'),
('soup_029', '酸辣湯', 'soup', '酸っぱ辛いスープ', 'chinese', 'normal', 25, 'egg', 500, '["具材を煮る", "黒酢とラー油で味付け", "溶き卵を流す"]', '[]', '["spicy"]', '["spring","summer","autumn","winter"]'),
('soup_030', 'きのこスープ', 'soup', 'きのこたっぷりスープ', 'western', 'easy', 25, 'other', 300, '["きのこを炒める", "コンソメで煮る"]', '[]', '["clear"]', '["autumn","winter"]');
